#!/bin/bash
# Copyright 2009-2016 Victor Boyko, Tashkent, Uzbekistan <bvoid(at)yandex.ru>
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#  THIS SOFTWARE FOR NON COMMERCIAL USING ONLY.


e='echo -e'
b=`basename $0`
ROOT_DIR=${ROOT_DIR:-/}

fail_exit() {
  $e "$1"
  exit 1
}

if [ -r /etc/pkgman.conf ]; then
  . /etc/pkgman.conf
else
  fail_exit "${b}:  configuration file /etc/pkgman.conf not readable, exit!"
fi

if [ ! $1 ]; then
  $e "\033[1;33mUsage:\033[0;0m $b PKGINFILE [&]

where,
  PKGINFILE = file with list of installed files in form \"find .\"
              (e.g. installed with \"pkg_in\")
  & = set to background mode
  [TODO]
  - = send content to stdout (usefully with netcat).

Allow variable:
  PKG_R = directory to store \"rolled\" packages (default $PKG_R)
  ROOT_DIR = target directory with installed files (default is \"$ROOT_DIR\")

-----------------------------------------
Simple packages roller for (B)LFS systems
* $b provided without implied warranty"
  exit 1
fi

if [ ! -r "$PKG_R" ] ; then
  mkdir -p "$PKG_R" || fail_exit \
   "${b}:  no access for creating directory \"$PKG_R\", exit!"
elif [ ! -w "$PKG_R" ] ; then
  fail_exit "${b}:  no write access for output directory \"$PKG_R\", exit!"
fi  

for p in "$@" ; do
	L=`basename "$p"`
	cd "$ROOT_DIR"
  $e -n "${b}:  creating $PKG_R/${L}.pkg.txz ..."
  tar cfJ $PKG_R/${L}.pkg.txz --ignore-failed-read --no-recursion -T "$p" \
    &>/dev/null || fail_exit "\n${b}:  tar failed, exit!"
  $e "\033[1;32m done\033[0;0m"
done
