#!/bin/bash
# Copyright 2009-2016 Victor Boyko, Tashkent, Uzbekistan <bvoid(at)yandex.ru>
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#  THIS SOFTWARE FOR NON COMMERCIAL USING ONLY.


e='echo -e'
b=`basename $0`
ROOT_DIR=${ROOT_DIR:-/}

fail_exit() {
  $e "$1"
  exit 1
}

if [ -r /etc/pkgman.conf ]; then
  . /etc/pkgman.conf
else
  fail_exit "${b}:  configuration file /etc/pkgman.conf not readable, exit!"
fi

TRGT="${ROOT_DIR}${PKG_I}"

if [ ! $1 ]; then
  $e "\033[1;33mUsage: $b PKG [PKG2...] [-]\033[0;0m

where,
  PKG = archive(s), created with \"pkg_make\"
  [TODO]
  - = read content from stdin (usefully with netcat).

Allow variables:
  PKG_I = directory, where storing installed package's info (default \"$PKG_I\")
  ROOT_DIR = target directory for installing files (default is \"$ROOT_DIR\")

-------------------------------------------
Simple package installer for (B)LFS systems
* $b provided without implied warranty"
  exit 1
fi

if [ ! -r "$TRGT" ] ; then
  mkdir -p "$TRGT" || fail_exit \
   "${b}:  no access for creating directory \"$TRGT\", exit!"
elif [ ! -w "$TRGT" ] ; then
  fail_exit "${b}:  no write access for target directory \"$TRGT\", exit!"
fi

for p in "$@" ; do
  if [ ! -r "$p" ] ; then
    $e "${b}:  not found \"$p\", skip"
  else
    L=`basename "$p" |sed -e 's/$*\.pkg\.t.z//'`

    $e -n "${b}:  installing ${L} ..."
    tar xvf $p -C "$ROOT_DIR" 2>/dev/null | sort 2>/dev/null > $TRGT/$L || fail_exit \
     "\n${b}:  tar failed, exit!"
    $e "\033[1;32m done\033[0;0m"

    if [ -f "$TRGT/${L}.in" ]; then
      if [ "$ROOT_DIR" = "/" ]; then
        pushd "$ROOT_DIR" &>/dev/null
        sh "$TRGT/${L}.in"
        popd &>/dev/null
      else
        $e "\n${b}:  ${L}.in not executed in non-native root target, skip"
      fi
    fi
  fi
done
