#!/bin/bash
# Copyright 2009-2016 Victor Boyko, Tashkent, Uzbekistan <bvoid(at)yandex.ru>
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#  THIS SOFTWARE FOR NON COMMERCIAL USING ONLY.


e='echo -e'
b=`basename $0`
ROOT_DIR=${ROOT_DIR:-/}

fail_exit() {
  $e "$1"
  exit 1
}

if [ -r /etc/pkgman.conf ]; then
  . /etc/pkgman.conf
else
  fail_exit "${b}:  configuration file /etc/pkgman.conf not readable, exit!"
fi

TRGT="${ROOT_DIR}${PKG_O}"

if [ ! $1 ]; then
  $e "\033[1;33mUsage:\033[0;0m $b PKGINFILE [&]

where,
  PKGINFILE = file(s) with list of installed files in form \"find .\"
              (e.g. installed with \"pkg_in\")
  & = set to background mode

Allow variable:
  PKG_O = directory, where storing removed package's info (default \"$PKG_O\")
  ROOT_DIR = target directory with installed files (default is \"$ROOT_DIR\")

------------------------------------------
Simple packages remover for (B)LFS systems
* $b provided without implied warranty"
  exit 1
fi

if [ ! -r "$TRGT" ] ; then
  mkdir -p "$TRGT" || fail_exit \
   "${b}:  no access for creating directory \"$TRGT\", exit!"
elif [ ! -w "$TRGT" ] ; then
  fail_exit "${b}:  no write access for target directory \"$TRGT\", exit!"
fi

for p in "$@" ; do
  if [ ! -r "$p" ] ; then
    $e "${b}:  not found \"$p\", skip"
  else
    ( cd "$ROOT_DIR"
    L=`basename ${p}`
    
    if [ -f ${p}.out ]; then
      mv -f ${p}.out "$TRGT" &>/dev/null || fail_exit \
       "${b}:  cannot save .out script (permission denied?), exit!"
    fi
    if [ -f ${p}.in ]; then
      mv -f ${p}.in "$TRGT" &>/dev/null || fail_exit \
       "${b}:  cannot save .in script (permission denied?), exit!"
    fi
    
    if [ -f ${p}*.log.* ]; then
      mv -f ${p}*.log.* "$TRGT" &>/dev/null
    fi
    
    $e -n "${b}:  removing `basename "$p"` ..."
    p_lst="$(< $p)"
    $e -n " files ..."
    for target in $p_lst; do
      if [ ! -d "$target" ] || [ -L "$target" ]; then
        rm -f "$target" &>/dev/null
      fi
    done
    $e -n " dirs ..."
    for target in $p_lst; do
      if [ -d "$target" ]; then
        rmdir -p "$target" &>/dev/null
      fi
    done
    mv -f "$p" "$TRGT" &>/dev/null || fail_exit \
     "\n${b}:  cannot save PKGINFILE (permission denied?), exit!"
    $e "\033[1;32m done\033[0;0m"
    
    if [ -f $TRGT/${L}.out ]; then
      sh $TRGT/${L}.out
    fi )
  fi
done
