#!/bin/bash
# Copyright 2009-2016 Victor Boyko, Tashkent, Uzbekistan <bvoid(at)yandex.ru>
# All rights reserved.
#
# Redistribution and use of this script, with or without modification, is
# permitted provided that the following conditions are met:
#
# 1. Redistributions of this script must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#
#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR IMPLIED
#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#  THIS SOFTWARE FOR NON COMMERCIAL USING ONLY.


e='echo -e'
b=`basename $0`
ROOT_DIR=${ROOT_DIR:-/}

fail_exit() {
  $e "$1"
  exit 1
}

if [ -r /etc/pkgman.conf ]; then
  . /etc/pkgman.conf
else
  fail_exit "${b}:  configuration file /etc/pkgman.conf not readable, exit!"
fi

TRGT="${ROOT_DIR}${PKG_I}"

if [ ! $1 ]; then
  $e "\033[1;33mUsage:\033[0;0m $b PKGNAME [&]

where,
  PKGNAME = package name and version (example \"bash-4.3\")
  & = set to background mode

  Usage $b in directory with package's files (e.g.
  installed after \"make install DESTDIR=\`pwd\`/PKG\")

Allow variables:
  ROOT_DIR = target directory for installing files (default is \"$ROOT_DIR\")
  PKG_I = directory, where storing installed package's info (default \"$PKG_I\")
  PKG_A = architecture suffix (default \"$PKG_A\")

----------------------------------------------------
Simple package's files transfer for (B)LFS GNU/Linux
* $b provided without implied warranty"
  exit 1
fi

if [ ! -r "$TRGT" ] ; then
  mkdir -p "$TRGT" || fail_exit \
   "${b}:  no access for creating directory \"$TRGT\", exit!"
elif [ ! -w "$TRGT" ] ; then
  fail_exit "${b}:  no write access for output directory \"$TRGT\", exit!"
fi

$e -n "${b}:  copying package's files to ${ROOT_DIR} ..."
find . |sort > $TRGT/${1}-${PKG_A} ||fail checkin-std
cp -fa --remove-destination * ${ROOT_DIR} 2>/dev/null || fail_exit \
  "${b}:  copying failed, exit!"
if [ -r $TRGT/${1}-${PKG_A}.in ]; then
  pushd / &>/dev/null
  sh $TRGT/${1}-${PKG_A}.in
  popd &>/dev/null
fi
$e "\033[1;32m done\033[0;0m"
